// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWK0tp_maXaXb7EjCr8IZzESif_2sCIPU',
    appId: '1:413192199332:web:a3b54ad0936e802576da31',
    messagingSenderId: '413192199332',
    projectId: 'primer-flutter-c6821',
    authDomain: 'primer-flutter-c6821.firebaseapp.com',
    storageBucket: 'primer-flutter-c6821.appspot.com',
    measurementId: 'G-QCV6EG2RVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBERKoU2UVvbCFgie0ihfAsopemgH_hSu8',
    appId: '1:413192199332:android:3c3cf3b01da58d2876da31',
    messagingSenderId: '413192199332',
    projectId: 'primer-flutter-c6821',
    storageBucket: 'primer-flutter-c6821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnC72QvkqM2qf-jAZbd2sCrrXVw_9YvcA',
    appId: '1:413192199332:ios:439e254bee99aef176da31',
    messagingSenderId: '413192199332',
    projectId: 'primer-flutter-c6821',
    storageBucket: 'primer-flutter-c6821.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnC72QvkqM2qf-jAZbd2sCrrXVw_9YvcA',
    appId: '1:413192199332:ios:439e254bee99aef176da31',
    messagingSenderId: '413192199332',
    projectId: 'primer-flutter-c6821',
    storageBucket: 'primer-flutter-c6821.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWK0tp_maXaXb7EjCr8IZzESif_2sCIPU',
    appId: '1:413192199332:web:c91933a61ef039ea76da31',
    messagingSenderId: '413192199332',
    projectId: 'primer-flutter-c6821',
    authDomain: 'primer-flutter-c6821.firebaseapp.com',
    storageBucket: 'primer-flutter-c6821.appspot.com',
    measurementId: 'G-ZWQCR782PC',
  );
}
